Repository maulanasdqn/pkm, pull requests merged in 2024-08, with the labels that each got.

#3 chore: clean up project structure
  apps/market/app/layout.tsx
  apps/market/specs/index.spec.tsx
  apps/tourism/specs/index.spec.tsx
Labels: enhancement

#4 feat: setup auth
  .github/workflows/ci.yml
  apps/market/app/layout.tsx
  apps/tourism/app/layout.tsx
  libs/auth/src/index.ts
  libs/auth/src/lib/auth.spec.tsx
  libs/auth/src/lib/auth.ts
  libs/auth/src/lib/auth.tsx
  libs/auth/src/lib/hello-server.tsx
  libs/auth/src/lib/index.ts
  libs/auth/src/lib/password.ts
  libs/auth/src/lib/provider.tsx
  libs/auth/src/lib/token.ts
  libs/auth/src/server.ts
Labels: enhancement, help wanted

#6 feat: setup storybook
  .gitignore
  apps/market/app/api/auth/[...nextauth]/route.ts
  apps/market/app/api/hello/route.ts
  apps/tourism/app/api/auth/[...nextauth]/route.ts
  components/ui/.eslintrc.json
  components/ui/.storybook/global.css
  components/ui/.storybook/main.ts
  components/ui/.storybook/preview.ts
  components/ui/design.ts
  components/ui/postcss.config.js
  components/ui/src/button/button.tsx
  components/ui/src/index.ts
  components/ui/src/lib/button/button.spec.tsx
  components/ui/src/lib/button/button.stories.tsx
  components/ui/src/lib/button/button.tsx
  components/ui/src/lib/button/index.ts
  components/ui/src/lib/button/type.ts
  components/ui/src/lib/input/index.ts
  components/ui/src/lib/input/input.spec.tsx
  components/ui/src/lib/input/input.tsx
  components/ui/tailwind.config.ts
  components/ui/tsconfig.json
  components/ui/tsconfig.lib.json
  components/ui/tsconfig.storybook.json
  libs/auth/src/lib/auth.ts
  libs/auth/src/lib/credential.ts
  libs/auth/src/lib/google.ts
  libs/clsx/package.json
  libs/clsx/rollup.config.js
  libs/clsx/src/lib/clsx.spec.tsx
  libs/clsx/src/lib/clsx.ts
  libs/clsx/src/lib/clsx.tsx
  libs/clsx/src/lib/hello-server.tsx
  libs/clsx/src/server.ts
  nx.json
  package.json
  yarn.lock
Labels: enhancement

#7 Up To Staging 11 Aug 2024
  .github/workflows/ci.yml
  .gitignore
  apps/market/app/api/auth/[...nextauth]/route.ts
  apps/market/app/api/hello/route.ts
  apps/market/app/layout.tsx
  apps/tourism/app/api/auth/[...nextauth]/route.ts
  apps/tourism/app/layout.tsx
  apps/tourism/specs/index.spec.tsx
  components/ui/.eslintrc.json
  components/ui/.storybook/global.css
  components/ui/.storybook/main.ts
  components/ui/.storybook/preview.ts
  components/ui/design.ts
  components/ui/postcss.config.js
  components/ui/src/button/button.spec.tsx
  components/ui/src/button/button.tsx
  components/ui/src/index.ts
  components/ui/src/lib/button/button.spec.tsx
  components/ui/src/lib/button/button.stories.tsx
  components/ui/src/lib/button/button.tsx
  components/ui/src/lib/button/index.ts
  components/ui/src/lib/button/type.ts
  components/ui/src/lib/input/index.ts
  components/ui/src/lib/input/input.spec.tsx
  components/ui/src/lib/input/input.tsx
  components/ui/tailwind.config.ts
  components/ui/tsconfig.json
  components/ui/tsconfig.lib.json
  components/ui/tsconfig.storybook.json
  libs/auth/src/index.ts
  libs/auth/src/lib/auth.spec.tsx
  libs/auth/src/lib/auth.ts
  libs/auth/src/lib/auth.tsx
  libs/auth/src/lib/credential.ts
  libs/auth/src/lib/google.ts
  libs/auth/src/lib/hello-server.tsx
  libs/auth/src/lib/index.ts
  libs/auth/src/lib/password.ts
  libs/auth/src/lib/provider.tsx
  libs/auth/src/lib/token.ts
  libs/auth/src/server.ts
  libs/clsx/package.json
  libs/clsx/rollup.config.js
  libs/clsx/src/lib/clsx.spec.tsx
  libs/clsx/src/lib/clsx.ts
  libs/clsx/src/lib/clsx.tsx
  libs/clsx/src/lib/hello-server.tsx
  libs/clsx/src/server.ts
  nx.json
  package.json
  yarn.lock
Labels: documentation, enhancement

#8 Up To Production 11 Aug 2024
  .github/workflows/ci.yml
  .gitignore
  apps/market/app/api/auth/[...nextauth]/route.ts
  apps/market/app/api/hello/route.ts
  apps/market/app/layout.tsx
  apps/tourism/app/api/auth/[...nextauth]/route.ts
  apps/tourism/app/layout.tsx
  apps/tourism/specs/index.spec.tsx
  components/ui/.eslintrc.json
  components/ui/.storybook/global.css
  components/ui/.storybook/main.ts
  components/ui/.storybook/preview.ts
  components/ui/design.ts
  components/ui/postcss.config.js
  components/ui/src/button/button.spec.tsx
  components/ui/src/button/button.tsx
  components/ui/src/index.ts
  components/ui/src/lib/button/button.spec.tsx
  components/ui/src/lib/button/button.stories.tsx
  components/ui/src/lib/button/button.tsx
  components/ui/src/lib/button/index.ts
  components/ui/src/lib/button/type.ts
  components/ui/src/lib/input/index.ts
  components/ui/src/lib/input/input.spec.tsx
  components/ui/src/lib/input/input.tsx
  components/ui/tailwind.config.ts
  components/ui/tsconfig.json
  components/ui/tsconfig.lib.json
  components/ui/tsconfig.storybook.json
  libs/auth/src/index.ts
  libs/auth/src/lib/auth.spec.tsx
  libs/auth/src/lib/auth.ts
  libs/auth/src/lib/auth.tsx
  libs/auth/src/lib/credential.ts
  libs/auth/src/lib/google.ts
  libs/auth/src/lib/hello-server.tsx
  libs/auth/src/lib/index.ts
  libs/auth/src/lib/password.ts
  libs/auth/src/lib/provider.tsx
  libs/auth/src/lib/token.ts
  libs/auth/src/server.ts
  libs/clsx/package.json
  libs/clsx/rollup.config.js
  libs/clsx/src/lib/clsx.spec.tsx
  libs/clsx/src/lib/clsx.ts
  libs/clsx/src/lib/clsx.tsx
  libs/clsx/src/lib/hello-server.tsx
  libs/clsx/src/server.ts
  nx.json
  package.json
  yarn.lock
Labels: documentation, enhancement

#9 feat: setup husky
  .husky/pre-commit
  apps/market/types/next-auth.d.ts
  apps/tourism/app/global.css
  apps/tourism/app/layout.tsx
  apps/tourism/types/next-auth.d.ts
  libs/auth/src/types/next-auth.d.ts
  libs/entities/src/index.ts
  libs/entities/src/lib/entities.spec.tsx
  libs/entities/src/lib/entities.tsx
  libs/entities/src/lib/hello-server.tsx
  libs/entities/src/lib/token.ts
  libs/entities/src/lib/user.ts
  libs/entities/src/server.ts
  package.json
  yarn.lock
Labels: enhancement

#10 feat: add button and adjust design token
  components/ui/design.ts
  components/ui/src/lib/button/button.spec.tsx
  components/ui/src/lib/button/button.stories.tsx
  components/ui/src/lib/button/button.tsx
  components/ui/src/lib/button/type.ts
  package.json
  yarn.lock
Labels: enhancement

#11 feat: add input textfield
  .husky/common.sh
  .husky/pre-commit
  apps/market/app/page.tsx
  apps/market/design.ts
  components/ui/design.ts
  components/ui/src/index.ts
  components/ui/src/lib/input/index.ts
  components/ui/src/lib/input/input.spec.tsx
  components/ui/src/lib/input/input.tsx
  components/ui/src/lib/inputs/index.ts
  components/ui/src/lib/inputs/textfield/index.ts
  components/ui/src/lib/inputs/textfield/textfield.stories.tsx
  components/ui/src/lib/inputs/textfield/textfield.tsx
  components/ui/src/lib/inputs/textfield/type.ts
  package.json
  yarn.lock
Labels: enhancement

#13 refactor(button): remove yellow variant then add color props
  apps/tourism/app/page.tsx
  apps/tourism/design.ts
  components/ui/src/lib/button/button.stories.tsx
  components/ui/src/lib/button/button.tsx
  components/ui/src/lib/button/type.ts
Labels: documentation, enhancement

#15 feat: add alert
  apps/market/app/page.tsx
  components/ui/.storybook/global.css
  components/ui/src/lib/atoms/alert/alert.spec.tsx
  components/ui/src/lib/atoms/alert/alert.stories.tsx
  components/ui/src/lib/atoms/alert/alert.tsx
  components/ui/src/lib/atoms/alert/index.ts
  components/ui/src/lib/atoms/alert/type.ts
  components/ui/src/lib/atoms/index.ts
  package.json
  yarn.lock
Labels: enhancement

#21 Feat/market landing
  .eslintrc.json
  .github/workflows/ci.yml
  .husky/pre-commit
  apps/market/app/(landing)/_modules/index.tsx
  apps/market/app/(landing)/_modules/sections/activity/index.tsx
  apps/market/app/(landing)/_modules/sections/index.ts
  apps/market/app/(landing)/_modules/sections/our-product/index.tsx
  apps/market/app/(landing)/layout.tsx
  apps/market/app/(landing)/page.tsx
  apps/market/app/(landing)/products/_modules/index.tsx
  apps/market/app/(landing)/products/page.tsx
  apps/market/app/auth/layout.tsx
  apps/market/app/page.tsx
  apps/market/public/images/big-card-market.webp
  apps/market/public/images/fb.webp
  apps/market/public/images/ig.webp
  apps/market/public/images/kerajinan.webp
  apps/market/public/images/kesehatan.webp
  apps/market/public/images/kopi.webp
  apps/market/public/images/perikanan.webp
  apps/market/public/images/perkebunan.webp
  apps/market/public/images/pertanian.webp
  apps/market/public/images/peternakan.webp
  apps/market/public/images/sample-activity-2.webp
  apps/market/public/images/sample-activity-3.webp
  apps/market/public/images/sample-activity.webp
  apps/market/public/images/sample-hero.webp
  apps/market/public/images/wa.webp
  apps/market/public/images/yt.webp
  apps/tourism/app/auth/layout.tsx
  components/ui/src/lib/atoms/alert/alert.tsx
  components/ui/src/lib/atoms/button/button.tsx
  components/ui/src/lib/atoms/button/type.ts
  components/ui/src/lib/atoms/cards/cards.spec.tsx
  components/ui/src/lib/atoms/cards/cards.tsx
  components/ui/src/lib/atoms/cards/index.ts
  components/ui/src/lib/atoms/cards/type.ts
  components/ui/src/lib/atoms/footers/footers.stories.tsx
  components/ui/src/lib/atoms/footers/footers.tsx
  components/ui/src/lib/atoms/footers/index.ts
  components/ui/src/lib/atoms/index.ts
  components/ui/src/lib/atoms/inputs/textfield/textfield.tsx
  components/ui/src/lib/molecules/navbars/navbars.tsx
  components/ui/src/lib/molecules/navbars/type.ts
  nx.json
  package.json
  yarn.lock
Labels: enhancement

#22 feat(tourism): add tours page and detail page (finished)
  apps/tourism/app/(landing-page)/page.tsx
  apps/tourism/app/(landing-page)/tours/[id]/_modules/index.tsx
  apps/tourism/app/(landing-page)/tours/[id]/page.tsx
  apps/tourism/app/(landing-page)/tours/_modules/index.tsx
  apps/tourism/app/(landing-page)/tours/page.tsx
  apps/tourism/public/icons/map-icon.svg
  apps/tourism/public/images/bg-lake.webp
  apps/tourism/public/images/lake-2.png
  apps/tourism/public/images/lake-3.png
  apps/tourism/public/images/lake-4.png
  components/ui/src/lib/atoms/carousel/carousel.tsx
  components/ui/src/lib/atoms/carousel/type.ts
  components/ui/src/lib/molecules/footers/footer-tourism.tsx
Labels: enhancement

#23 feat: detail product & about page
  apps/market/app/(landing)/_modules/index.tsx
  apps/market/app/(landing)/_modules/sections/activity/index.tsx
  apps/market/app/(landing)/_modules/sections/our-product/index.tsx
  apps/market/app/(landing)/_modules/sections/our-product/products.tsx
  apps/market/app/(landing)/about/_modules/index.tsx
  apps/market/app/(landing)/about/_modules/sections/activity/index.tsx
  apps/market/app/(landing)/about/_modules/sections/index.ts
  apps/market/app/(landing)/about/_modules/sections/mission/index.tsx
  apps/market/app/(landing)/about/page.tsx
  apps/market/app/(landing)/layout.tsx
  apps/market/app/(landing)/products/[id]/_modules/index.tsx
  apps/market/app/(landing)/products/[id]/layout.tsx
  apps/market/app/(landing)/products/[id]/page.tsx
  apps/market/app/(landing)/products/_modules/index.tsx
  apps/market/next.config.js
  apps/market/public/images/sample-about-2.webp
  apps/market/public/images/sample-about-3.webp
  apps/market/public/images/sample-about.webp
  apps/market/public/images/sample-hero-2.webp
  apps/market/public/images/sample-hero-3.webp
  apps/market/public/images/sample-mission.webp
  components/ui/src/lib/atoms/auto-slider/index.ts
  components/ui/src/lib/atoms/auto-slider/slider.tsx
  components/ui/src/lib/atoms/auto-slider/type.ts
  components/ui/src/lib/atoms/button/button.tsx
  components/ui/src/lib/atoms/button/type.ts
  components/ui/src/lib/atoms/cards/cards.tsx
  components/ui/src/lib/atoms/footers/footers.tsx
  components/ui/src/lib/atoms/footers/index.ts
  components/ui/src/lib/atoms/index.ts
  components/ui/src/lib/molecules/footers/footers-market.stories.tsx
  components/ui/src/lib/molecules/footers/footers-market.tsx
  components/ui/src/lib/molecules/footers/index.ts
  components/ui/src/lib/molecules/navbars/navbars.tsx
  components/ui/src/lib/organisms/hero-banner/hero.tsx
  components/ui/src/lib/organisms/hero-banner/index.ts
  components/ui/src/lib/organisms/hero-banner/type.ts
  components/ui/src/lib/organisms/index.ts
  package.json
Labels: enhancement

#25 feat: market category page & integration register market
  apps/market/app/(landing)/_modules/index.tsx
  apps/market/app/(landing)/categories/[id]/page.tsx
  apps/market/app/(landing)/categories/_modules/index.tsx
  apps/market/app/auth/login/_modules/index.tsx
  apps/market/app/auth/register/_modules/index.tsx
  apps/market/public/images/sample-categories.webp
  components/ui/src/lib/atoms/alert/alert.tsx
  components/ui/src/lib/atoms/alert/type.ts
  components/ui/src/lib/atoms/button/button.stories.tsx
  components/ui/src/lib/atoms/button/button.tsx
  components/ui/src/lib/atoms/button/type.ts
  components/ui/src/lib/molecules/form-auth/form.tsx
  components/ui/src/lib/molecules/form-auth/types.ts
  components/ui/src/lib/molecules/navbars/navbars.tsx
  libs/auth/src/lib/market/auth.ts
  libs/auth/src/lib/market/credential.ts
  libs/auth/src/lib/market/util.ts
  libs/drizzle/src/lib/market/config.ts
  libs/drizzle/src/lib/market/connection.ts
  libs/drizzle/src/lib/market/migrations/0000_yellow_khan.sql
  libs/drizzle/src/lib/market/migrations/meta/0000_snapshot.json
  libs/drizzle/src/lib/market/migrations/meta/_journal.json
  libs/drizzle/src/lib/market/schema.ts
  libs/entities/src/index.ts
  libs/entities/src/lib/market/index.ts
  libs/entities/src/lib/market/schema.ts
  package.json
  yarn.lock
Labels: enhancement

#26 fix(tourism): fixed input at reservation ticket
  apps/tourism/app/(landing-page)/reservation/[id]/_modules/sections/create-reservation-section/index.tsx
  components/ui/src/lib/atoms/button/button.tsx
  components/ui/src/lib/atoms/button/type.ts
  components/ui/src/lib/atoms/calendar/calendar.stories.tsx
  components/ui/src/lib/atoms/calendar/calendar.tsx
  components/ui/src/lib/atoms/calendar/type.ts
  components/ui/src/lib/atoms/popover/popover.stories.tsx
  components/ui/src/lib/atoms/popover/popover.tsx
  components/ui/src/lib/atoms/popover/type.ts
  components/ui/src/lib/molecules/date-picker/date-picker.tsx
Labels: enhancement

#36 feat: integrasi login admin & carts page
  apps/market/app/(landing)/carts/_modules/index.tsx
  apps/market/app/(landing)/carts/layout.tsx
  apps/market/app/(landing)/carts/page.tsx
  apps/market/app/auth/layout.tsx
  apps/market/app/auth/login/_modules/index.tsx
  apps/market/app/auth/register/_modules/index.tsx
  apps/market/app/layout.tsx
  components/ui/src/lib/atoms/cards/cart-market/card.spec.tsx
  components/ui/src/lib/atoms/cards/cart-market/card.tsx
  components/ui/src/lib/atoms/cards/cart-market/index.ts
  components/ui/src/lib/atoms/cards/cart-market/type.ts
  components/ui/src/lib/atoms/cards/index.ts
  components/ui/src/lib/atoms/inputs/checkbox/checkbox.tsx
  components/ui/src/lib/atoms/inputs/checkbox/index.ts
  components/ui/src/lib/atoms/inputs/checkbox/type.ts
  components/ui/src/lib/atoms/inputs/index.ts
  components/ui/src/lib/atoms/inputs/textarea/textarea.tsx
  components/ui/src/lib/molecules/card-cart/card.tsx
  components/ui/src/lib/molecules/card-cart/index.ts
  components/ui/src/lib/molecules/card-cart/type.ts
  components/ui/src/lib/molecules/index.ts
  components/ui/src/lib/molecules/navbars/navbars.tsx
  libs/actions/src/lib/market/auth/index.ts
  libs/actions/src/lib/market/auth/login.ts
  libs/actions/src/lib/market/index.ts
  libs/auth/src/lib/common/provider.tsx
  libs/auth/src/lib/market/auth.ts
  libs/auth/src/lib/market/util.ts
  libs/entities/src/lib/user.ts
Labels: enhancement

#37 fix(tourism):fix landingpage navigation
  apps/tourism/app/(admin)/dashboard/tour/_modules/index.tsx
  apps/tourism/app/(admin)/dashboard/tour/_modules/sections/index.ts
  apps/tourism/app/(admin)/dashboard/tour/_modules/sections/tour-form/index.tsx
  apps/tourism/app/(admin)/dashboard/tour/_modules/sections/tour-form/type.ts
  apps/tourism/app/(admin)/dashboard/tour/_modules/sections/tour-list/index.tsx
  apps/tourism/app/(landing-page)/_modules/sections/destination-section/index.tsx
  apps/tourism/app/(landing-page)/_modules/sections/news-section/index.tsx
  apps/tourism/app/(landing-page)/news/_modules/sections/news-list-section/index.tsx
  apps/tourism/app/(landing-page)/reservation/_modules/sections/cek-reservation-section/index.tsx
  apps/tourism/app/(landing-page)/tours/[id]/_modules/index.tsx
  apps/tourism/app/(landing-page)/tours/_modules/index.tsx
  components/ui/src/lib/atoms/dialog/dialog.tsx
  components/ui/src/lib/atoms/dialog/index.ts
  components/ui/src/lib/atoms/index.ts
  components/ui/src/lib/atoms/table/index.ts
  components/ui/src/lib/atoms/table/table.tsx
  components/ui/src/lib/molecules/navbars/navbars.tsx
  components/ui/src/lib/molecules/sidebars/sidebar.tsx
  components/ui/src/lib/organisms/reservation-cards/reservation-cards.tsx
  package.json
  yarn.lock
Labels: enhancement
